/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    NarBar: typeof import('./components/NarBar.vue')['default']
    PanelHtml: typeof import('./components/panel/PanelHtml.vue')['default']
    PanelOutputCss: typeof import('./components/panel/PanelOutputCss.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
    TitleBar: typeof import('./components/TitleBar.vue')['default']
  }
}
