import type { Preset } from 'unocss'
export default function Samuui(): Preset {
  return {
    name: 'unocss-samu-ui',
    shortcuts:[
      { 'space-vertical':'[flex-flow:column_nowrap]' },
      [/^btn-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 shadow-sm text-white dark:text-gray-900 bg-${c}-500 hover:bg-${c}-600 disabled:bg-${c}-500 disabled:hover:bg-${c}-500 dark:bg-${c}-400 dark:hover:bg-${c}-500 dark:disabled:bg-${c}-400 dark:disabled:hover:bg-${c}-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-${c}-500 dark:focus-visible:outline-${c}-400 inline-flex items-center`],
      [/^btn-outline-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 ring-1 ring-inset ring-current text-${c}-500 dark:text-${c}-400 hover:bg-${c}-50 disabled:bg-transparent dark:hover:bg-${c}-950 dark:disabled:bg-transparent focus-visible:ring-2 focus-visible:ring-${c}-500 dark:focus-visible:ring-${c}-400 inline-flex items-center`],
      [/^btn-soft-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 text-${c}-500 dark:text-${c}-400 bg-${c}-50 hover:bg-${c}-100 disabled:bg-${c}-50 dark:bg-${c}-950 dark:hover:bg-${c}-900 dark:disabled:bg-${c}-950 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-${c}-500 dark:focus-visible:ring-${c}-400 inline-flex items-center`],
      [/^btn-ghost-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 text-${c}-500 dark:text-${c}-400 hover:bg-${c}-50 disabled:bg-transparent dark:hover:bg-${c}-950 dark:disabled:bg-transparent focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-${c}-500 dark:focus-visible:ring-${c}-400 inline-flex items-center`],
      [/^btn-link-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 text-${c}-500 hover:text-${c}-600 disabled:text-${c}-500 dark:text-${c}-400 dark:hover:text-${c}-500 dark:disabled:text-${c}-400 underline-offset-4 hover:underline focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-${c}-500 dark:focus-visible:ring-${c}-400 inline-flex items-center`],
      [/^btn-black-((rose|pink|fuchsia|purple|violet|indigo|blue|sky|cyan|teal|emerald|green|lime|yellow|amber|orange|red|gray|slate|zinc|neutral|stone|light|dark|lightblue|warmgray|truegray|coolgray|bluegray))$/, ([, c])=> `focus:outline-none focus-visible:outline-0 disabled:cursor-not-allowed disabled:opacity-75 flex-shrink-0 font-medium rounded-md text-sm gap-x-1.5 px-2.5 py-1.5 shadow-sm text-white dark:text-gray-900 bg-${c}-500 hover:bg-${c}-600 disabled:bg-${c}-500 dark:bg-${c}-400 dark:hover:bg-${c}-500 dark:disabled:bg-${c}-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-${c}-500 dark:focus-visible:outline-${c}-400 w-full flex justify-center items-center`],
      [/^btn-size-((2xs))$/, ([, c])=>{
        return ''
      }],
      [/^space-((start|center|end|between|around|evenly|stretch))$/, ([, c])=> `flex justify-${c} gap-[8px_12px] [flex-flow:row_wrap]`],
    ],
    rules: [
      ['btn-size-2xs', { 'font-size': '0.75rem','line-height': '1rem' }],
    ]
  }
}
