export interface Options {
  lightPrimary: string
  lightPrimaryFocus: string
  lightPrimaryContent: string
  lightSecondary: string
  lightSecondaryFocus: string
  lightSecondaryContent: string
  lightAccent: string
  lightAccentFocus: string
  lightAccentContent: string
  lightNeutral: string
  lightNeutralFocus: string
  lightNeutralContent: string
  lightBase100: string
  lightBase200: string
  lightBase300: string
  lightBaseContent: string
  lightInfo: string
  lightInfoContent: string
  lightSuccess: string
  lightSuccessContent: string
  lightWarning: string
  lightWarningContent: string
  lightError: string
  lightErrorContent: string
  darkPrimary: string
  darkPrimaryFocus: string
  darkPrimaryContent: string
  darkSecondary: string
  darkSecondaryFocus: string
  darkSecondaryContent: string
  darkAccent: string
  darkAccentFocus: string
  darkAccentContent: string
  darkNeutral: string
  darkNeutralFocus: string
  darkNeutralContent: string
  darkBase100: string
  darkBase200: string
  darkBase300: string
  darkBaseContent: string
  darkInfo: string
  darkInfoContent: string
  darkSuccess: string
  darkSuccessContent: string
  darkWarning: string
  darkWarningContent: string
  darkError: string
  darkErrorContent: string
  badge: string
  box: string
  paddingCard: string
  collapseFocus: string
}

export const config: Required<Options> = {
  lightPrimary: '#570DF8',
  lightPrimaryFocus: '#4406CB',
  lightPrimaryContent: '#FFFFFF',
  lightSecondary: '#F000B8',
  lightSecondaryFocus: '#C00093',
  lightSecondaryContent: '#FFFFFF',
  lightAccent: '#37CDBE',
  lightAccentFocus: '#2AA69A',
  lightAccentContent: '#163835',
  lightNeutral: '#3D4451',
  lightNeutralFocus: '#313641',
  lightNeutralContent: '#FFFFFF',
  lightBase100: '#FFFFFF',
  lightBase200: '#F2F2F2',
  lightBase300: '#E5E6E6',
  lightBaseContent: '#1F2937',
  lightInfo: '#3ABFF8',
  lightInfoContent: '#002B3D',
  lightSuccess: '#36D399',
  lightSuccessContent: '#003320',
  lightWarning: '#FBBD23',
  lightWarningContent: '#382800',
  lightError: '#F87272',
  lightErrorContent: '#470000',
  darkPrimary: '#661AE6',
  darkPrimaryFocus: '#5114B9',
  darkPrimaryContent: '#FFFFFF',
  darkSecondary: '#D926AA',
  darkSecondaryFocus: '#AE1E88',
  darkSecondaryContent: '#FFFFFF',
  darkAccent: '#1FB2A5',
  darkAccentFocus: '#198E84',
  darkAccentContent: '#FFFFFF',
  darkNeutral: '#191D24',
  darkNeutralFocus: '#111318',
  darkNeutralContent: '#A6ADBB',
  darkBase100: '#2A303C',
  darkBase200: '#242933',
  darkBase300: '#20252E',
  darkBaseContent: '#A6ADBB',
  darkInfo: '#3ABFF8',
  darkInfoContent: '#002B3D',
  darkSuccess: '#36D399',
  darkSuccessContent: '#003320',
  darkWarning: '#FBBD23',
  darkWarningContent: '#382800',
  darkError: '#F87272',
  darkErrorContent: '#470000',
  badge: '1.9rem',
  box: '1rem',
  paddingCard: '2rem',
  collapseFocus: '222.86 17.073% 8.0392%'
}
