name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm run lint

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
